version: '3.8'

services:
    cook-book-postgres:
        image: postgres:16.1
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            POSTGRES_USER: '${POSTGRES_USER:-user}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
            POSTGRES_DB: '${POSTGRES_DB:-cook-book}'
        volumes:
            - ./cook-book-db:/var/lib/postgresql/data
    
    cook-book-redis:
        image: redis:7.2.3
        ports:
            - '${REDIS_PORT:-6379}:6379'
        command: >
            --requirepass '${REDIS_PASSWORD:-redispass}'
        restart: unless-stopped
    
    cook-book-s3:
        image: quay.io/minio/minio:latest
        command: server /data --console-address ":9001"
        restart: unless-stopped
        ports:
            - "7001:9001"
        volumes:
            - ./cook-book-s3-data:/usr/src/app/s3
        environment:
            - MINIO_ROOT_USER=user
            - MINIO_ROOT_PASSWORD=password

volumes:
    cook-book-db:
    cook-book-s3-data:
