export enum DishCategoryEnum {
  SOUP = 'Soup',
  MAIN_MEAT = 'Main - Meat',
  MAIN_FISH = 'Main - Fish',
  MAIN_VEGETARIAN = 'Main - Vegetarian',
  SNACK_COLD = 'Snack - Cold',
  SNACK_HOT = 'Snack - Hot',
  SNACK_CANAPE = 'Snack - Canape',
  SALAD_VEGETABLE = 'Salad - Vegetable',
  SALAD_MEAT = 'Salad - Meat',
  SALAD_FRUIT = 'Salad - Fruit',
  SAUCE_MEAT = 'Sauce - Meat',
  SAUCE_FISH = 'Sauce - Fish',
  SAUCE_SALAD = 'Sauce - Salad',
  DESSERT = 'Dessert',
  BAKERY_CAKES = 'Bakery - Cakes',
  BAKERY_COOKIES = 'Bakery - Cookies',
  BAKERY_PIES = 'Bakery - Pies',
  DRINK_ALCOHOLIC = 'Drink - Alcoholic',
  DRINK_NON_ALCOHOLIC = 'Drink - Non-Alcoholic',
  PRESERVATION_FRUIT = 'Preservation - Fruit',
  PRESERVATION_VEGETABLE = 'Preservation - Vegetable',
}
